# Generated by Django 4.1.7 on 2024-03-18 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mohafaza', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PublicSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SectorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corruption_type', models.CharField(choices=[('فساد سياسي', 'فساد سياسي'), ('  تأثيرات سلبية على استقلالية القضاء', ' تأثيرات سلبية على استقلالية القضاء'), ('فساد قانوني', 'فساد قانوني'), ('احتكار', 'احتكار'), ('تقصير أو اهمال في توفير السلامة', 'تقصير أو اهمال في توفير السلامة '), ('فساد بيئي.', 'فساد بيئي.'), ('فساد مالي', 'فساد مالي'), (' تجاوز السلطة', ' تجاوز السلطة'), ('فساد اداري', 'فساد اداري'), ('فساد عقاري', 'فساد عقاري'), ('انتهاكات حقوق انسان', 'انتهاكات حقوق انسان'), ('تغطية', 'تغطية'), ('فساد تعييني', 'فساد تعييني'), ('فساد في العقود ', 'فساد في العقود '), ('تقييد حرية التعبير', 'تقييد حرية التعبير'), ('اهمال', 'اهمال'), ('اختلاس الأموال العامة', 'اختلاس الأموال العامة'), ('جريمة', 'جريمة'), ('سوء ادارة', 'سوء ادارة'), ('عدم الشفافية', 'عدم الشفافية'), ('فساد سلوكي / فساد أخلاقي', 'فساد سلوكي / فساد أخلاقي'), (' تلاعب بالصفقات', 'لاعب بالصفقات'), ('تهديدات عنيفة', 'تهديدات عنيفة'), ('بيروقراطية', 'بيروقراطية'), ('انحياز واستغلال الموقف', 'انحياز واستغلال الموقف'), ('تزوير واستعمال مزور', 'تزوير واستعمال مزور'), ('اتهامات بالاختلاس وغسيل الأموال', 'اتهامات بالاختلاس وغسيل الأموال'), ('احتكار', 'احتكار'), ('قمع ', ' قمع'), (' زيادة الأسعار بصورة غير مبررة', ' زيادة الأسعار بصورة غير مبررة'), (' سرقة ', ' سرقة'), ('التهريب', ' التهريب'), (' الفساد  المرتبط بالأحزاب السياسية والمسؤولين', ' الفساد المرتبط بالأحزاب السياسية والمسؤولين'), (' تقصير', ' تقصير')], max_length=100)),
                ('date_of_incident', models.DateTimeField()),
                ('report_source', models.CharField(choices=[('مباشر', 'مباشر'), ('غير مباشر', 'غير مباشر'), ('مجهول', 'مجهول')], max_length=100)),
                ('incident_frequency', models.CharField(choices=[('مرة واحدة', 'مرة واحدة'), ('شهري', 'شهري'), ('أسبوعي', 'أسبوعي'), ('يومي', 'يومي')], max_length=100)),
                ('impact_level', models.CharField(choices=[('فردي', 'فردي'), ('مجتمعي', 'مجتمعي'), ('وطني', 'وطني')], max_length=100)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.location')),
                ('public_sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.publicsector')),
            ],
        ),
        migrations.AddField(
            model_name='publicsector',
            name='sector_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_sectors', to='report.sectortype'),
        ),
    ]

