# Generated by Django 4.1.7 on 2024-03-30 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_remove_publicsector_sector_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='impact_level',
        ),
        migrations.RemoveField(
            model_name='report',
            name='incident_frequency',
        ),
        migrations.RemoveField(
            model_name='report',
            name='report_source',
        ),
    ]
