# Generated by Django 4.1.7 on 2024-04-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_alter_report_corruption_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='public_sector_type',
            field=models.CharField(choices=[('hospitals', 'مستشفيات'), ('ministries', 'وزارات'), ('institutions', 'مؤسسات'), ('banks', 'بنوك'), ('prisons', 'سجون'), ('courts', 'محاكم'), ('universities', 'جامعات'), ('security_institutions', 'الأمن العام')], default='', max_length=100),
        ),
    ]
